spring.application.name=spring-ai-introduction
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-5
spring.ai.openai.chat.options.temperature=1